version: "3.7"

x-logging: &loki-logging
  driver: json-file
  options:
    tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"

services:

  app:
    container_name: app
    hostname: app
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        DJANGO_SUPERUSER_PASSWORD: ${ENV_APP_DJANGO_SUPERUSER_PASSWORD}
        DJANGO_SUPERUSER_USERNAME: ${ENV_APP_DJANGO_SUPERUSER_USERNAME}
        DJANGO_SUPERUSER_EMAIL: ${ENV_APP_DJANGO_SUPERUSER_EMAIL}
    env_file:
      - .env
    command: bash -c '/srv/app/startapp.sh'
    environment:
      DJANGO_SUPERUSER_PASSWORD: ${ENV_APP_DJANGO_SUPERUSER_PASSWORD}
      DJANGO_SUPERUSER_USERNAME: ${ENV_APP_DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_EMAIL: ${ENV_APP_DJANGO_SUPERUSER_EMAIL}
    ports:
      - "7654:7654"
    volumes:
      - ./:/usr/src/app
      - ./data:/srv/app/data
    labels:
      - traefik.http.routers.app.rule=Host(`app.${ENV_APP_DOCKER_DOMAIN}`)
      - traefik.http.routers.app.service=app
      # - traefik.http.routers.app.middlewares=auth
      - traefik.http.services.app.loadbalancer.server.port=7654
      - traefik.http.routers.app.entrypoints=https
      - traefik.http.routers.app.tls=true
      - traefik.http.routers.app.tls.certresolver=${ENV_APP_DOCKER_CERT_RESOLVER}
    networks:
      - internalnetwork
    restart: always
    logging: *loki-logging

networks:
  internalnetwork:
    name: internalnetwork
    external: true
